spring:
  ######################################
  #  flyway 数据库版本化配置
  ######################################
  flyway:
    baseline-version: 1.0.0
    baseline-on-migrate: true
    encoding: UTF-8
    clean-disabled: true
    validate-on-migrate: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
    locations: classpath:db/migration
    table: flyway_schema_history
    enabled: true

