# spring boot 配置
server:
  port: ${port:9997}

spring:
  application:
    name: 'agent-ollama-vision'
  # spring ai 相关配置
  ai:
    ######################################
    # Spring AI observability settings
    ######################################
    chat:
      client:
        observations:
          log-prompt: true
      observations:
        # 记录大模型输出
        log-prompt: true
        # 记录大模型提示词
        log-completion: true
    ######################################
    # Spring AI 模型配置
    ######################################
    ollama:
      chat:
        options:
          model: 'gemma3:4b'
      #base-url: 'http://192.168.10.100:11434'
      base-url: 'http://127.0.0.1:11434'
      init:
        pull-model-strategy: WHEN_MISSING
        chat:
          additional-models:
            - gemma3:4b
    ######################################
    # Host Agent: Spring AI 模型配置 阿里千问 openai接口规范
    ######################################
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: 使用自己的key
      chat:
        base-url: ${spring.ai.openai.base-url}
        api-key: ${spring.ai.openai.api-key}
        options:
          model: 'qwen-vl-max-latest'


card-url: 'http://127.0.0.1'
######################################
#  musaemotion A2A Card 配置
######################################
musaemotion:
  a2a:
    server:
      capabilities:
        push-notifications: true
        streaming: false
      skills:
        - id: 'visionSkill'
          name: 'visionSkill'
          description: '图像视觉识别'
          examples:
            - '请帮我分析一下这张图片的内容'
      url: ${card-url}:${server.port}
      version: '1.0.0'
      default-input-modes:
         - 'text'
         - 'image/png'
      default-output-modes:
         - 'text'
      # name 只能使用英文
      name: 'imageVision'
      description: '图像视觉识别'




